### ISSUE TITLE
Azure OpenAI API KEY 支持

### ISSUE THREAD

**Issue by racy2020** [draJiang/scouter-extension#1]
希望能够支持 Azure OpenAI

当前 Azure OpenAI 的 Endpoint 无法使用，提示 "🥲 Resource not found"

**Comment by draJiang** [comment]
> 希望能够支持 Azure OpenAI
> 
> 当前 Azure OpenAI 的 Endpoint 无法使用，提示 "🥲 Resource not found"

嗨，最新版本中已经支持了 Azure OpenAI，可以试试看。
